#ifndef _SD_CONFIG_H_
#define _SD_CONFIG_H_

#define SD_UI_TIME_LINE_HEADER_HEIGHT 30

#define SD_UI_ANIMATION_WIDGET_MIN_HEIGHT 240
#define SD_UI_ANIMATION_RULER_START 250
#define SD_UI_ANIMATION_RULER_GAP 10



#endif /*_SD_CONFIG_H_*/
