#ifndef _SD_CONFIG_H_
#define _SD_CONFIG_H_


#define SD_UI_COMMON_ICON_SIZE 16

#define SD_UI_TIME_LINE_HEADER_HEIGHT 30


#define SD_UI_ANIMATION_WIDGET_MIN_HEIGHT 240

#define SD_UI_ANIMATION_RULER_START 250
#define SD_UI_ANIMATION_RULER_GAP 10

#define SD_UI_ANIMATION_RULER_EYE_AREA 40
#define SD_UI_ANIMATION_RULER_HEIGHT 30

#define SD_UI_ANIMATION_RULER_EXPAND_X 60


#define SD_UI_ANIMATION_RULER_NAME_X 80

#define SD_UI_ANIMATION_SUB_RULER_ICON_X 65
#define SD_UI_ANIMATION_SUB_RULER_NAME_X 85


#define SD_ANIMATION_DEFAULT_FPS 12







#endif /*_SD_CONFIG_H_*/
