#include "SnThemeConfig.h"

NS_FS_USE

Color SnThemeConfig::VIEW_AXIS_X_COLOR;
Color SnThemeConfig::VIEW_AXIS_Y_COLOR;
float SnThemeConfig::VIEW_AXIS_WIDTH;

Color SnThemeConfig::SELECT_CONTROLLER_SELECTED_COLOR;
Color SnThemeConfig::IDENTIFY_SELECT_OUT_LINE_COLOR;

float SnThemeConfig::IDENTIFY_SELECT_OUT_LINE_WIDTH;

/* translate */
Color SnThemeConfig::TRANSLATE_CONTROLLER_CENTER_POINT_COLOR;
Color SnThemeConfig::TRANSLATE_CONTROLLER_CENTER_POINT_COLOR_ONFOCUS;
Color SnThemeConfig::TRANSLATE_CONTROLLER_CENTER_POINT_OUT_LINE_COLOR;
float SnThemeConfig::TRANSLATE_CONTROLLER_CENTER_POINT_OUT_LINE_WIDTH;
float SnThemeConfig::TRANSLATE_CONTROLLER_CENTER_POINT_HIT_GAP;
float SnThemeConfig::TRANSLATE_CONTROLLER_AXIS_HIT_WIDTH;
float SnThemeConfig::TRANSLATE_CONTROLLER_AXIS_HIT_LONG;

float SnThemeConfig::TRANSLATE_CONTROLLER_AXIS_WIDTH;
Faeris::Color SnThemeConfig::TRANSLATE_CONTROLLER_X_AXIS_COLOR;
Faeris::Color SnThemeConfig::TRANSLATE_CONTROLLER_Y_AXIS_COLOR;

Faeris::Color SnThemeConfig::TRANSLATE_CONTROLLER_X_AXIS_FOCUS_COLOR;
Faeris::Color SnThemeConfig::TRANSLATE_CONTROLLER_Y_AXIS_FOCUS_COLOR;

float SnThemeConfig::TRANSLATE_CONTROLLER_TRIANGLE_HEIGHT;
float SnThemeConfig::TRANSLATE_CONTROLLER_TRIANGLE_WIDTH;


/* scale */
float SnThemeConfig::SCALE_CONTROLLER_CENTER_POINT_HIT_GAP;
Faeris::Color SnThemeConfig::SCALE_CONTROLLER_CENTER_POINT_COLOR;
Faeris::Color SnThemeConfig::SCALE_CONTROLLER_CENTER_POINT_COLOR_ONFOCUS;
Faeris::Color SnThemeConfig::SCALE_CONTROLLER_CENTER_POINT_OUT_LINE_COLOR;

Faeris::Color SnThemeConfig::SCALE_CONTROLLER_X_AXIS_COLOR;
Faeris::Color SnThemeConfig::SCALE_CONTROLLER_Y_AXIS_COLOR;
Faeris::Color SnThemeConfig::SCALE_CONTROLLER_X_AXIS_FOCUS_COLOR;
Faeris::Color SnThemeConfig::SCALE_CONTROLLER_Y_AXIS_FOCUS_COLOR;

float SnThemeConfig::SCALE_CONTROLLER_AXIS_WIDTH;
float SnThemeConfig::SCALE_CONTROLLER_CENTER_POINT_OUT_LINE_WIDTH;
float SnThemeConfig::SCALE_CONTROLLER_AXIS_HIT_WIDTH;
float SnThemeConfig::SCALE_CONTROLLER_AXIS_HIT_LONG;
float SnThemeConfig::SCALE_CONTROLLER_AXIS_RECT_SIZE;

/* rotate */
Faeris::Color SnThemeConfig::ROTATE_CONTROLLER_OUT_LINE_COLOR;
float SnThemeConfig::ROTATE_CONTROLLER_RADIUS;
float SnThemeConfig::ROTATE_CONTROLLER_OUT_LINE_WIDTH;

float SnThemeConfig::ROTATE_CONTROLLER_TRIANGLE_WIDTH;
float SnThemeConfig::ROTATE_CONTROLLER_TRIANGLE_HEIGHT;

Faeris::Color SnThemeConfig::ROTATE_CONTROLLER_OUT_LINE_FOCUS_COLOR;


/* resize */


float SnThemeConfig::RESIZE_CONTROLLER_HIT_LENGTH;
float SnThemeConfig::RESIZE_CONTROLLER_RECTANCLE_LENGTH;
float SnThemeConfig::RESIZE_CONTROLLER_OUT_LINE_WIDTH;

Faeris::Color SnThemeConfig::RESIZE_CONTROLLER_OUT_LINE_COLOR;
Faeris::Color SnThemeConfig::RESIZE_CONTROLLER_FILL_COLOR;
Faeris::Color SnThemeConfig::RESIZE_CONTROLLER_FILL_FOCUS_COLOR;




void SnThemeConfig::initConfig()
{
	VIEW_AXIS_X_COLOR=Color::RED;
	VIEW_AXIS_Y_COLOR=Color::BLUE;
	VIEW_AXIS_WIDTH=1.0f;

	SELECT_CONTROLLER_SELECTED_COLOR=Color(0,100,220,120);

	IDENTIFY_SELECT_OUT_LINE_COLOR=Color(0,100,220,250);

	IDENTIFY_SELECT_OUT_LINE_WIDTH=2.0f;

	/* translate */
	TRANSLATE_CONTROLLER_CENTER_POINT_COLOR=Color(0,100,220,120);
	TRANSLATE_CONTROLLER_CENTER_POINT_OUT_LINE_COLOR=Color(0,100,220,255);
	TRANSLATE_CONTROLLER_CENTER_POINT_COLOR_ONFOCUS=Color(255,255,0,120);
	TRANSLATE_CONTROLLER_CENTER_POINT_OUT_LINE_WIDTH=1.0f;
	TRANSLATE_CONTROLLER_CENTER_POINT_HIT_GAP=10.0f;

	TRANSLATE_CONTROLLER_AXIS_HIT_WIDTH=8.0f;
	TRANSLATE_CONTROLLER_AXIS_HIT_LONG=116.0f;

	TRANSLATE_CONTROLLER_X_AXIS_COLOR=Color::RED;
	TRANSLATE_CONTROLLER_Y_AXIS_COLOR=Color::GREEN;

	TRANSLATE_CONTROLLER_X_AXIS_FOCUS_COLOR=Color(255,255,0);
	TRANSLATE_CONTROLLER_Y_AXIS_FOCUS_COLOR=Color(255,255,0);


	TRANSLATE_CONTROLLER_AXIS_WIDTH=2.0f;

	TRANSLATE_CONTROLLER_TRIANGLE_HEIGHT=12;
	TRANSLATE_CONTROLLER_TRIANGLE_WIDTH=16;


	/* scale */
	SCALE_CONTROLLER_CENTER_POINT_HIT_GAP=10.0f;
	SCALE_CONTROLLER_CENTER_POINT_COLOR=Color(0,100,200,120);
	SCALE_CONTROLLER_CENTER_POINT_COLOR_ONFOCUS=Color(255,255,0,120);
	SCALE_CONTROLLER_CENTER_POINT_OUT_LINE_COLOR=Color(0,100,200,255);

	SCALE_CONTROLLER_X_AXIS_COLOR=Color::RED;
	SCALE_CONTROLLER_Y_AXIS_COLOR=Color::GREEN;
	SCALE_CONTROLLER_X_AXIS_FOCUS_COLOR=Color(255,255,0);
	SCALE_CONTROLLER_Y_AXIS_FOCUS_COLOR=Color(255,255,0);

	SCALE_CONTROLLER_AXIS_WIDTH=2.0f;
	SCALE_CONTROLLER_CENTER_POINT_OUT_LINE_WIDTH=1.0f;
	SCALE_CONTROLLER_AXIS_HIT_WIDTH=8.0f;
	SCALE_CONTROLLER_AXIS_HIT_LONG=116.0f;
	SCALE_CONTROLLER_AXIS_RECT_SIZE=12.0f;


	/* rotate */
	ROTATE_CONTROLLER_OUT_LINE_COLOR=Color(255,0,0);
	ROTATE_CONTROLLER_OUT_LINE_FOCUS_COLOR=Color(255,255,0);
	ROTATE_CONTROLLER_RADIUS=54.0f;
	ROTATE_CONTROLLER_OUT_LINE_WIDTH=3.0f;

	ROTATE_CONTROLLER_TRIANGLE_WIDTH=16;
	ROTATE_CONTROLLER_TRIANGLE_HEIGHT=12;

	/* resize */
	RESIZE_CONTROLLER_HIT_LENGTH=6;
	RESIZE_CONTROLLER_RECTANCLE_LENGTH=4;
	RESIZE_CONTROLLER_OUT_LINE_WIDTH=2;

	RESIZE_CONTROLLER_OUT_LINE_COLOR=Color(0,100,200,250);
	RESIZE_CONTROLLER_FILL_COLOR=Color(255,255,255,100);
	RESIZE_CONTROLLER_FILL_FOCUS_COLOR=Color(255,255,0,255);

}
