#include "SnThemeConfig.h"

NS_FS_USE

Color SnThemeConfig::VIEW_AXIS_X_COLOR;
Color SnThemeConfig::VIEW_AXIS_Y_COLOR;
float SnThemeConfig::VIEW_AXIS_WIDTH;

Color SnThemeConfig::SELECT_CONTROLLER_SELECTED_COLOR;
Color SnThemeConfig::IDENTIFY_SELECT_OUT_LINE_COLOR;

float SnThemeConfig::IDENTIFY_SELECT_OUT_LINE_WIDTH;
Color SnThemeConfig::TRANSLATE_CONTROLLER_CENTER_POINT_COLOR;
Color SnThemeConfig::TRANSLATE_CONTROLLER_CENTER_POINT_COLOR_ONFOCUS;
Color SnThemeConfig::TRANSLATE_CONTROLLER_CENTER_POINT_OUT_LINE_COLOR;
float SnThemeConfig::TRANSLATE_CONTROLLER_CENTER_POINT_OUT_LINE_WIDTH;
float SnThemeConfig::TRANSLATE_CONTROLLER_CENTER_POINT_HIT_GAP;
float SnThemeConfig::TRANSLATE_CONTROLLER_AXIS_HIT_WIDTH;
float SnThemeConfig::TRANSLATE_CONTROLLER_AXIS_HIT_LONG;

float SnThemeConfig::TRANSLATE_CONTROLLER_AXIS_WIDTH;
Faeris::Color SnThemeConfig::TRANSLATE_CONTROLLER_X_AXIS_COLOR;
Faeris::Color SnThemeConfig::TRANSLATE_CONTROLLER_Y_AXIS_COLOR;

Faeris::Color SnThemeConfig::TRANSLATE_CONTROLLER_X_AXIS_FOCUS_COLOR;
Faeris::Color SnThemeConfig::TRANSLATE_CONTROLLER_Y_AXIS_FOCUS_COLOR;

float SnThemeConfig::TRANSLATE_CONTROLLER_TRIANGLE_HEIGHT;
float SnThemeConfig::TRANSLATE_CONTROLLER_TRIANGLE_WIDTH;

void SnThemeConfig::initConfig()
{
	VIEW_AXIS_X_COLOR=Color::RED;
	VIEW_AXIS_Y_COLOR=Color::BLUE;
	VIEW_AXIS_WIDTH=1.0f;

	SELECT_CONTROLLER_SELECTED_COLOR=Color(0,100,220,120);

	IDENTIFY_SELECT_OUT_LINE_COLOR=Color(0,100,220,250);

	IDENTIFY_SELECT_OUT_LINE_WIDTH=2.0f;

	TRANSLATE_CONTROLLER_CENTER_POINT_COLOR=Color(0,100,220,120);
	TRANSLATE_CONTROLLER_CENTER_POINT_OUT_LINE_COLOR=Color(0,100,220,255);
	TRANSLATE_CONTROLLER_CENTER_POINT_COLOR_ONFOCUS=Color(255,255,0,120);
	TRANSLATE_CONTROLLER_CENTER_POINT_OUT_LINE_WIDTH=1.0f;
	TRANSLATE_CONTROLLER_CENTER_POINT_HIT_GAP=10.0f;

	TRANSLATE_CONTROLLER_AXIS_HIT_WIDTH=8.0f;
	TRANSLATE_CONTROLLER_AXIS_HIT_LONG=116.0f;

	TRANSLATE_CONTROLLER_X_AXIS_COLOR=Color::RED;
	TRANSLATE_CONTROLLER_Y_AXIS_COLOR=Color::GREEN;

	TRANSLATE_CONTROLLER_X_AXIS_FOCUS_COLOR=Color(255,255,0);
	TRANSLATE_CONTROLLER_Y_AXIS_FOCUS_COLOR=Color(255,255,0);


	TRANSLATE_CONTROLLER_AXIS_WIDTH=2.0f;

	TRANSLATE_CONTROLLER_TRIANGLE_HEIGHT=12;
	TRANSLATE_CONTROLLER_TRIANGLE_WIDTH=16;

}
